name: Deactivate

on:
  pull_request:
    types: [ closed ]

jobs:
  prune:
    name: Deactivate environment
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-deactivate@v1
        with:
          kube-config: ${{ secrets.KUBECONFIG }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
